import userModel from "./src/models/userModel"
import postModel from "./src/models/postModel"

// test data set

const userTest = [{  
  password: 'mypassword0',
  studentId: 10001,
  email: '10001@korea.ac.kr',
  firstMajor: 'mathematics',
  name: 'Hong gil dong',
  nickname: 'Hong',
  role: 'candidate',
},
{ password: 'mypassword1',
  studentId: 10002,
  email: '10002@korea.ac.kr',
  firstMajor: 'computer science',
  name: 'Oh gil dong',
  nickname: 'Oh',
  role: 'candidate',
}, 
{ password: 'mypassword2',
  studentId: 10003,
  email: '10003@korea.ac.kr',
  firstMajor: 'Korean',
  name: 'Oh dong dong',
  nickname: 'Oh2',
  role: 'passer',
},
{ password: 'mypassword3',
  studentId: 10004,
  email: '10004@korea.ac.kr',
  firstMajor: 'mathematics',
  name: 'park dong dong',
  nickname: 'park',
  role: 'passer',
}];

const postTest = [{  
  userId: '1234',
  category: 'computer Science talk',
  title: 'common asking', 
  content: 'do you have any license?',
},
{ userId: '2341',
  category: 'computer Science talk',
  title: 'major asking', 
  content: 'can you recommend? what subject is honey',
},
{ userId: '3412',
  category: 'mathematics talk',
  title: 'major asking', 
  content: 'math is shit',
},
{ userId: '4123',
  category: 'mathematics talk',
  title: 'major asking', 
  content: 'geomatric prof. is too salty',
}];
